---
Name: socialnavconfig
---
## YML Config
SilverStripe\Control\Controller:
  extensions:
    -  Toast\Social\SocialNavControllerExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Toast\Social\SocialNavSiteConfigExtension

