---
Name: socialnavconfig
---
## YML Config
SilverStripe\Control\Controller:
  extensions:
    - SocialNavControllerExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SocialNavSiteConfigExtension

